CREATE TABLE "users" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR(150) NOT NULL,
	"email" VARCHAR(100) NOT NULL UNIQUE,
	"password" TEXT NOT NULL,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "urls"(
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER REFERENCES "users"("id"),
	"url" TEXT NOT NULL,
	"shortUrl" TEXT UNIQUE,
	"visitCount" INTEGER NOT NULL DEFAULT 0,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "sessions"(
	"id" SERIAL PRIMARY KEY,
	"userId" INTEGER REFERENCES "users"("id"),
	"token" TEXT NOT NULL UNIQUE,
	"createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);